Repository elchininet/postcss-rtlcss, pull requests merged in 2024-04, with the labels that each got.

#293 Fix 'PostcCSS' → 'PostCSS' typo in README
  README.md
Labels: documentation, fix

#300 Split aliases variables in different snapshots
  package.json
  pnpm-lock.yaml
  tests/__snapshots__/aliases-variables/combined/aliases-default.snapshot
  tests/__snapshots__/aliases-variables/combined/aliases-map.snapshot
  tests/__snapshots__/aliases-variables/combined/process-env-false.snapshot
  tests/__snapshots__/aliases-variables/combined/process-env-true.snapshot
  tests/__snapshots__/aliases-variables/combined/wrong-aliases.snapshot
  tests/__snapshots__/aliases-variables/diff/aliases-default.snapshot
  tests/__snapshots__/aliases-variables/diff/aliases-map.snapshot
  tests/__snapshots__/aliases-variables/diff/process-env-false.snapshot
  tests/__snapshots__/aliases-variables/diff/process-env-true.snapshot
  tests/__snapshots__/aliases-variables/diff/wrong-aliases.snapshot
  tests/__snapshots__/aliases-variables/override/aliases-default.snapshot
  tests/__snapshots__/aliases-variables/override/aliases-map.snapshot
  tests/__snapshots__/aliases-variables/override/process-env-false.snapshot
  tests/__snapshots__/aliases-variables/override/process-env-true.snapshot
  tests/__snapshots__/aliases-variables/override/wrong-aliases.snapshot
  tests/__snapshots__/variables.test.ts.snap
  tests/aliases-variables.test.ts
  tests/utils/index.ts
Labels: Configuration

#302 Split basic options test snapshots
  tests/__snapshots__/basic-options.test.ts.snap
  tests/__snapshots__/basic-options/combined/basic.snapshot
  tests/__snapshots__/basic-options/combined/process-keyframes-true.snapshot
  tests/__snapshots__/basic-options/combined/process-url-true.snapshot
  tests/__snapshots__/basic-options/combined/source-rtl-and-process-keyframes-true.snapshot
  tests/__snapshots__/basic-options/combined/source-rtl.snapshot
  tests/__snapshots__/basic-options/combined/use-calc-true.snapshot
  tests/__snapshots__/basic-options/diff/basic.snapshot
  tests/__snapshots__/basic-options/diff/process-keyframes-true.snapshot
  tests/__snapshots__/basic-options/diff/process-url-true.snapshot
  tests/__snapshots__/basic-options/diff/source-rtl-and-process-keyframes-true.snapshot
  tests/__snapshots__/basic-options/diff/source-rtl.snapshot
  tests/__snapshots__/basic-options/diff/use-calc-true.snapshot
  tests/__snapshots__/basic-options/override/basic.snapshot
  tests/__snapshots__/basic-options/override/process-keyframes-true.snapshot
  tests/__snapshots__/basic-options/override/process-url-true.snapshot
  tests/__snapshots__/basic-options/override/source-rtl-and-process-keyframes-true.snapshot
  tests/__snapshots__/basic-options/override/source-rtl.snapshot
  tests/__snapshots__/basic-options/override/use-calc-true.snapshot
  tests/basic-options.test.ts
Labels: Configuration

#303 Split empty rules test snapshot into multiple files
  tests/__snapshots__/empty-rules.test.ts.snap
  tests/__snapshots__/empty-rules/combined/basic.snapshot
  tests/__snapshots__/empty-rules/diff/basic.snapshot
  tests/__snapshots__/empty-rules/override/basic.snapshot
  tests/empty-rules.test.ts
Labels: Configuration

#304 Split nested rules test snapshots into different files
  tests/__snapshots__/nested-rules.test.ts.snap
  tests/__snapshots__/nested-rules/combined/source-ltr-process-rule-names-true.snapshot
  tests/__snapshots__/nested-rules/combined/source-ltr.snapshot
  tests/__snapshots__/nested-rules/combined/source-rtl-process-rule-names-true.snapshot
  tests/__snapshots__/nested-rules/combined/source-rtl.snapshot
  tests/__snapshots__/nested-rules/diff/source-ltr-process-rule-names-true.snapshot
  tests/__snapshots__/nested-rules/diff/source-ltr.snapshot
  tests/__snapshots__/nested-rules/diff/source-rtl-process-rule-names-true.snapshot
  tests/__snapshots__/nested-rules/diff/source-rtl.snapshot
  tests/__snapshots__/nested-rules/override/source-ltr-process-rule-names-true.snapshot
  tests/__snapshots__/nested-rules/override/source-ltr.snapshot
  tests/__snapshots__/nested-rules/override/source-rtl-process-rule-names-true.snapshot
  tests/__snapshots__/nested-rules/override/source-rtl.snapshot
  tests/nested-rules.test.ts
Labels: Configuration

#305 Split no-flip tests snapshots into multiple files
  tests/__snapshots__/noflip.test.ts.snap
  tests/__snapshots__/noflip/combined/no-flip.snapshot
  tests/__snapshots__/noflip/diff/no-flip.snapshot
  tests/__snapshots__/noflip/override/no-flip.snapshot
  tests/noflip.test.ts
Labels: Configuration

#306 Split overriding tests snapshots into different files
  tests/__snapshots__/overriding.test.ts.snap
  tests/__snapshots__/overriding/combined/basic.snapshot
  tests/__snapshots__/overriding/combined/with-safe-both-prefix.snapshot
  tests/__snapshots__/overriding/diff/basic.snapshot
  tests/__snapshots__/overriding/diff/with-safe-both-prefix.snapshot
  tests/__snapshots__/overriding/override/basic.snapshot
  tests/__snapshots__/overriding/override/with-safe-both-prefix.snapshot
  tests/overriding.test.ts
Labels: Configuration

#307 Split prefixed tests snapshots into multiple files
  tests/__snapshots__/prefixed.test.ts.snap
  tests/__snapshots__/prefixed/combined/custom-prefixes.snapshot
  tests/__snapshots__/prefixed/combined/ignore-prefixed-rules-false.snapshot
  tests/__snapshots__/prefixed/combined/prefixed-default.snapshot
  tests/__snapshots__/prefixed/combined/prefixed-with-array.snapshot
  tests/__snapshots__/prefixed/diff/custom-prefixes.snapshot
  tests/__snapshots__/prefixed/diff/ignore-prefixed-rules-false.snapshot
  tests/__snapshots__/prefixed/diff/prefixed-default.snapshot
  tests/__snapshots__/prefixed/diff/prefixed-with-array.snapshot
  tests/__snapshots__/prefixed/override/custom-prefixes.snapshot
  tests/__snapshots__/prefixed/override/ignore-prefixed-rules-false.snapshot
  tests/__snapshots__/prefixed/override/prefixed-default.snapshot
  tests/__snapshots__/prefixed/override/prefixed-with-array.snapshot
  tests/prefixed.test.ts
Labels: Configuration

#308 Split prefixes tests snapshots into multiple files
  tests/__snapshots__/prefixes.test.ts.snap
  tests/__snapshots__/prefixes/combined/custom-ltr-and-rtl-prefix-as-arrays.snapshot
  tests/__snapshots__/prefixes/combined/custom-ltr-and-rtl-prefix.snapshot
  tests/__snapshots__/prefixes/combined/custom-ltr-rtl-and-both-prefix-as-arrays-and-process-urls-true.snapshot
  tests/__snapshots__/prefixes/combined/prefix-selector-transformer-with-custom-ltr-and-rtl-prefixes.snapshot
  tests/__snapshots__/prefixes/combined/prefix-selector-transformer-with-default-prefixes.snapshot
  tests/__snapshots__/prefixes/diff/custom-ltr-and-rtl-prefix-as-arrays.snapshot
  tests/__snapshots__/prefixes/diff/custom-ltr-and-rtl-prefix.snapshot
  tests/__snapshots__/prefixes/diff/custom-ltr-rtl-and-both-prefix-as-arrays-and-process-urls-true.snapshot
  tests/__snapshots__/prefixes/diff/prefix-selector-transformer-with-custom-ltr-and-rtl-prefixes.snapshot
  tests/__snapshots__/prefixes/diff/prefix-selector-transformer-with-default-prefixes.snapshot
  tests/__snapshots__/prefixes/override/custom-ltr-and-rtl-prefix-as-arrays.snapshot
  tests/__snapshots__/prefixes/override/custom-ltr-and-rtl-prefix.snapshot
  tests/__snapshots__/prefixes/override/custom-ltr-rtl-and-both-prefix-as-arrays-and-process-urls-true.snapshot
  tests/__snapshots__/prefixes/override/prefix-selector-transformer-with-custom-ltr-and-rtl-prefixes.snapshot
  tests/__snapshots__/prefixes/override/prefix-selector-transformer-with-default-prefixes.snapshot
  tests/prefixes.test.ts
Labels: Configuration

#309 Split rule-names tests snapshots into multiple files
  tests/__snapshots__/rule-names.test.ts.snap
  tests/__snapshots__/rule-names/combined/process-rules-names-true-greedy-true.snapshot
  tests/__snapshots__/rule-names/combined/process-rules-names-true-source-rtl-greedy-true.snapshot
  tests/__snapshots__/rule-names/combined/process-rules-names-true-with-custom-string-map-and-greedy-true.snapshot
  tests/__snapshots__/rule-names/combined/process-rules-names-true-with-custom-string-map-rtl-and-greedy-true.snapshot
  tests/__snapshots__/rule-names/combined/process-rules-names-true-with-custom-string-map.snapshot
  tests/__snapshots__/rule-names/combined/process-rules-names-true.snapshot
  tests/__snapshots__/rule-names/diff/process-rules-names-true-greedy-true.snapshot
  tests/__snapshots__/rule-names/diff/process-rules-names-true-source-rtl-greedy-true.snapshot
  tests/__snapshots__/rule-names/diff/process-rules-names-true-with-custom-string-map-and-greedy-true.snapshot
  tests/__snapshots__/rule-names/diff/process-rules-names-true-with-custom-string-map-rtl-and-greedy-true.snapshot
  tests/__snapshots__/rule-names/diff/process-rules-names-true-with-custom-string-map.snapshot
  tests/__snapshots__/rule-names/diff/process-rules-names-true.snapshot
  tests/__snapshots__/rule-names/override/process-rules-names-true-greedy-true.snapshot
  tests/__snapshots__/rule-names/override/process-rules-names-true-source-rtl-greedy-true.snapshot
  tests/__snapshots__/rule-names/override/process-rules-names-true-with-custom-string-map-and-greedy-true.snapshot
  tests/__snapshots__/rule-names/override/process-rules-names-true-with-custom-string-map-rtl-and-greedy-true.snapshot
  tests/__snapshots__/rule-names/override/process-rules-names-true-with-custom-string-map.snapshot
  tests/__snapshots__/rule-names/override/process-rules-names-true.snapshot
  tests/rule-names.test.ts
Labels: Configuration

#310 Split safe-prefix tests snapshots into different files
  tests/__snapshots__/safe-prefix.test.ts.snap
  tests/__snapshots__/safe-prefix/combined/safe-both-prefix-true-process-keyframes-true.snapshot
  tests/__snapshots__/safe-prefix/combined/safe-both-prefix-true-process-urls-true.snapshot
  tests/__snapshots__/safe-prefix/combined/safe-both-prefix-true-rtl.snapshot
  tests/__snapshots__/safe-prefix/combined/safe-both-prefix-true.snapshot
  tests/__snapshots__/safe-prefix/diff/safe-both-prefix-true-process-keyframes-true.snapshot
  tests/__snapshots__/safe-prefix/diff/safe-both-prefix-true-process-urls-true.snapshot
  tests/__snapshots__/safe-prefix/diff/safe-both-prefix-true-rtl.snapshot
  tests/__snapshots__/safe-prefix/diff/safe-both-prefix-true.snapshot
  tests/__snapshots__/safe-prefix/override/safe-both-prefix-true-process-keyframes-true.snapshot
  tests/__snapshots__/safe-prefix/override/safe-both-prefix-true-process-urls-true.snapshot
  tests/__snapshots__/safe-prefix/override/safe-both-prefix-true-rtl.snapshot
  tests/__snapshots__/safe-prefix/override/safe-both-prefix-true.snapshot
  tests/safe-prefix.test.ts
Labels: Configuration

#311 Split string-map tests snapshots into multiple files
  tests/__snapshots__/string-map.test.ts.snap
  tests/__snapshots__/string-map/combined/custom-non-valid-string-different-lengths-map-process-urls-true.snapshot
  tests/__snapshots__/string-map/combined/custom-non-valid-string-different-types-map-process-urls-true.snapshot
  tests/__snapshots__/string-map/combined/custom-string-map-process-urls-true.snapshot
  tests/__snapshots__/string-map/combined/custom-string-map-without-names-process-urls-true.snapshot
  tests/__snapshots__/string-map/diff/custom-non-valid-string-different-lengths--map-process-urls-true.snapshot
  tests/__snapshots__/string-map/diff/custom-non-valid-string-different-lengths-map-process-urls-true.snapshot
  tests/__snapshots__/string-map/diff/custom-non-valid-string-different-types--map-process-urls-true.snapshot
  tests/__snapshots__/string-map/diff/custom-non-valid-string-different-types-map-process-urls-true.snapshot
  tests/__snapshots__/string-map/diff/custom-string-map-process-urls-true.snapshot
  tests/__snapshots__/string-map/diff/custom-string-map-without-names-process-urls-true.snapshot
  tests/__snapshots__/string-map/override/custom-non-valid-string-different-lengths--map-process-urls-true.snapshot
  tests/__snapshots__/string-map/override/custom-non-valid-string-different-lengths-map-process-urls-true.snapshot
  tests/__snapshots__/string-map/override/custom-non-valid-string-different-types--map-process-urls-true.snapshot
  tests/__snapshots__/string-map/override/custom-non-valid-string-different-types-map-process-urls-true.snapshot
  tests/__snapshots__/string-map/override/custom-string-map-process-urls-true.snapshot
  tests/__snapshots__/string-map/override/custom-string-map-without-names-process-urls-true.snapshot
  tests/string-map.test.ts
Labels: Configuration

#296 Make aliases affect both-prefixed and safe-prefixed declarations
  src/parsers/declarations.ts
  tests/__snapshots__/aliases-custom-declarations/combined/no-aliases-safe-both-prefix-false.snapshot
  tests/__snapshots__/aliases-custom-declarations/combined/no-aliases-safe-both-prefix-true.snapshot
  tests/__snapshots__/aliases-custom-declarations/combined/with-aliases-safe-both-prefix-false.snapshot
  tests/__snapshots__/aliases-custom-declarations/combined/with-aliases-safe-both-prefix-true.snapshot
  tests/__snapshots__/aliases-custom-declarations/diff/no-aliases-safe-both-prefix-false.snapshot
  tests/__snapshots__/aliases-custom-declarations/diff/no-aliases-safe-both-prefix-true.snapshot
  tests/__snapshots__/aliases-custom-declarations/diff/with-aliases-safe-both-prefix-false.snapshot
  tests/__snapshots__/aliases-custom-declarations/diff/with-aliases-safe-both-prefix-true.snapshot
  tests/__snapshots__/aliases-custom-declarations/override/no-aliases-safe-both-prefix-false.snapshot
  tests/__snapshots__/aliases-custom-declarations/override/no-aliases-safe-both-prefix-true.snapshot
  tests/__snapshots__/aliases-custom-declarations/override/with-aliases-safe-both-prefix-false.snapshot
  tests/__snapshots__/aliases-custom-declarations/override/with-aliases-safe-both-prefix-true.snapshot
  tests/aliases-custom-declarations.test.ts
  tests/constants/index.ts
  tests/css/input-aliases.css
Labels: fix

#312 Update changelog
  CHANGELOG.md
Labels: documentation
